### ISSUE TITLE
OpenAI compatible embedding API is not complete

### ISSUE THREAD

**Issue by npuichigo** [huggingface/text-embeddings-inference#106]
### Feature request

https://platform.openai.com/docs/api-reference/embeddings/create
As mentioned in document, array of integers or array of arrays of integers could also be the input.

### Motivation

Integrity

### Your contribution

I'm willing to contribute, but not sure how to be compatible with current design.

**Comment by nlaanait** [comment]
@npuichigo see #112 for a draft to add full-type compatibility with openai api within the current design.  
Appreciate your feedback!

**Comment by nlaanait** [comment]
@OlivierDehaene this issue should be closed since #214 has been merged.
