### ISSUE TITLE
artificially limiting chunk size to 512 tokens

### ISSUE THREAD

**Issue by m27315** [huggingface/text-embeddings-inference#107]
### System Info

I have tried several invocations of TEI, but this is the latest one I am using:
```
docker run --rm \
    --gpus all \
    -e CUDA_VISIBLE_DEVICES=0 \
    -e CUDA_MEMORY_FRACTION=0.5 \
    -e ANONYMIZED_TELEMETRY=False \
    -e HF_HUB_DISABLE_TELEMETRY=1 \
    --shm-size 2g \
    -p 8081:80 \
    -v /data/text-embeddings-inference-cache:/data \
    --name tei \
    --pull always \
    ghcr.io/huggingface/text-embeddings-inference:0.6 \
    --model-id BAAI/bge-large-en-v1.5 \
    --revision 351e66e4c00a2de7a511c0611f02fe0f56119c2b \
    --max-batch-tokens 1100 \
    --max-client-batch-size 1100 \
    --max-batch-requests 1 \
    --max-concurrent-requests 2
```

Hardware:
```
$ nvidia-smi
Tue Dec 12 17:04:52 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
|  0%   38C    P8              21W / 450W |  19921MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I am using an RTX 4090 on local GPU, and I am trying to vectorize a large number of data chunks.  The recursive chunk splitter creates these using a max-size of 1000.  Previously, I had been able to embed all of these chunks with langchain & Python using a call like:

```
embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-large-en-v1.5",
    model_kwargs={"device": "cuda"},
    encode_kwargs={"normalize_embeddings": True},
)
vectorstore = Chroma(
    collection_name="hello-there",
    embedding_function=embeddings,
    persist_directory="/data/storage",
)
...
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 100
chunks = [ ... RecursiveCharacterTextSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP).split_documents(... ]
...
BATCH_SIZE
vectorstore.add_documents(chunks[0:BATCH_SIZE])
```

The above works well; however, switching to use the local TEI instance fails:

```
embeddings = HuggingFaceHubEmbeddings(
    model="http://localhost:8081",
    huggingfacehub_api_token=os.environ.get("HUGGINGFACEHUB_API_TOKEN"),
)
... all else is unchanged ...
```

I have reduced the embedding batch size, `BATCH_SIZE`, from 500 to 1, but I always get this error from TEI:

```
2023-12-12T22:46:42.973630Z ERROR embed:embed{inputs="... 1000 tokens ..." truncate=false normalize=true}: text_embeddings_core::infer: core/src/infer.rs:110: Input validation error: `inputs` must have less than 512 tokens. Given: 553
```

The Python-lanchain app fails with an exception reporting similar:

```
Traceback (most recent call last):
  File "/data/myproject/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/data/myproject/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: http://localhost:8081/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/myproject/profluence_prep.py", line 189, in <module>
    vectorstore.add_documents(chunks[0:BATCH_SIZE])
  File "/data/myproject/venv/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 122, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/profluence-dev/venv/lib/python3.11/site-packages/langchain_community/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myproject/venv/lib/python3.11/site-packages/langchain_community/embeddings/huggingface_hub.py", line 94, in embed_documents
    responses = self.client.post(
                ^^^^^^^^^^^^^^^^^
  File "/data/myproject/venv/lib/python3.11/site-packages/huggingface_hub/inference/_client.py", line 240, in post
    hf_raise_for_status(response)
  File "/data/myproject/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 330, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 413 Client Error: Payload Too Large for url: http://localhost:8081/

Input validation error: `inputs` must have less than 512 tokens. Given: 553

```

### Workaround?

The only way I can fix this is to artificially reduce the chunk size, `CHUNK_SIZE`, to 500 tokens.

### Expected behavior

Why can I embed 500 docs, each up to 1000 tokens in size when using Chroma & langchain, but on the local GPU, same hardware with the same LLM model, I cannot embed a single doc with more than 512 tokens?

**Comment by OlivierDehaene** [comment]
It's because your original code implicitly truncate the inputs to 512 tokens behind your back while TEI throws an error if you don't explicitly ask for the input to be truncated by using the `truncate=true` argument.

```python
embeddings = HuggingFaceHubEmbeddings(
    model="http://localhost:8081",
    huggingfacehub_api_token=os.environ.get("HUGGINGFACEHUB_API_TOKEN"),
    model_kwargs = {"truncate": True}
)
```
should do the trick.

If I were you I would find a way to make sure the input is not truncated though (== inputs <= 512 tokens).

**Comment by OlivierDehaene** [comment]
> Why can I embed 500 docs, each up to 1000 tokens in size when using Chroma & langchain, but on the local GPU, same hardware with the same LLM model, I cannot embed a single doc with more than 512 tokens?

BTW, try rephrasing your question to avoid being sassy when asking for assistance.

**Comment by m27315** [comment]
Ahh, thanks for the explanation.  That makes sense now. ... I have reduced the chunk size, so data is not lost, but sadly, the answers got worse.  :open_mouth:  I'll have to puzzle that one a bit more. ... Sorry for coming across as sassy.  It's not my personality nor my intention.  I was trying to summarize or be succinct, but I'll give it more thought next time.  Thanks for the feedback.  :smile: ... I appreciate the good work.  TEI is an awesome project that has proven tremendously helpful. :+1:

**Comment by ibndias** [comment]
> Thanks for great project! Wish it supported more models like bge m3, nomic, etc.
> 
> In case it helps others, the above suggestion doesn't work. The langchain model_kwargs passes `parameters` through requests but needs to be `truncate` directly. i.e. with langchain==0.0.354 and TEI 0.6.0 I still get errors about too many tokens and logging shows truncate is false.
> 
> Additionally, TEI has a fixed client batch (default 32) but nominally langchain or the database doesn't know this. So have to set TEI to some reasonable (probably larger, like 4096) value and manually batch on client side if that is exceeded. But one has to ensure other limits are not exceeded: #50
> 
> This little child class works:
> 
> https://github.com/h2oai/h2ogpt/blob/04b7ee58ffbf7f3c9f0444ea0722cc982dc0212b/src/utils_langchain.py#L428-L462
> 
> Usage notes:
> 
> https://github.com/h2oai/h2ogpt/blob/04b7ee58ffbf7f3c9f0444ea0722cc982dc0212b/docs/FAQ.md#text-embedding-inference-server

Yes this is an issue with current langchain.
This workaround works for me, but setting auto truncate as true from TEI and gives user warning could be more easier https://github.com/huggingface/text-embeddings-inference/issues/218
