### ISSUE TITLE
Support NVIDIA A10G

### ISSUE THREAD

**Issue by RicardoHS** [huggingface/text-embeddings-inference#109]
### Feature request

There seems current docker images does not run over machines with an A10G like the ones provided by AWS. There is no much information about architecture or compute capabilities. It seems they use Ampere arch but some sources say they have 7.5 on compute capabilities. Nevertheless, no docker image in this repo seems to work, neither `text-embeddings-inference:turing-0.6`, `text-embeddings-inference:0.6` or `text-embeddings-inference:86-0.6`.

### Motivation

AWS provide a lot of Nvidia A10G gpus for they EC2 instances and they are the most used ones by far.

### Your contribution

When executing, it gives an Unknown error

```
│ 2023-12-14T20:28:23.986069Z  INFO text_embeddings_router: router/src/lib.rs:239: Starting model backend                                                                                                                                  │
│ thread 'main' panicked at /root/.cargo/git/checkouts/cudarc-a08d71fd9258e74e/c19522f/src/driver/safe/core.rs:51:24:                                                                                                                      │
│ called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_UNKNOWN, "unknown error")                                                                                                                                            │
│ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by OlivierDehaene** [comment]
Can you copy/past the output of running `nvidia-smi` on your instance?

**Comment by RicardoHS** [comment]
For giving some context in case it helps. Im executing `text-embeddings-inference` on EKS pods. The running AMI is `amazon-eks-gpu-node-1.26-v20230816` and the k8s cluster has enabled the `NVIDIA k8s-device-plugin` [link](https://github.com/NVIDIA/k8s-device-plugin#deployment-via-helm)

This is the output of `nvidia-smi` when I login in the running pod. The instance is a `g5.4xlarge` 
```
Mon Dec 18 11:38:31 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   20C    P8     8W / 300W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by RicardoHS** [comment]
Thank you for the unrelated support with this @OlivierDehaene . Just to completly close the issue regarding their initial problem. A NVIDIA A10G should run with `text-embeddings-inference:86-0.6` right?

**Comment by OlivierDehaene** [comment]
> A NVIDIA A10G should run with text-embeddings-inference:86-0.6 right?

Ideally yes, but the default image is also supported for A10.
