### ISSUE TITLE
There is no --cors-allow-origin flag and bind to 0.0.0.0 does not work

### ISSUE THREAD

**Issue by sandangel** [huggingface/text-embeddings-inference#110]
### System Info

```json
{"model_id":"BAAI/bge-large-en-v1.5","model_sha":"refs/pr/5","model_dtype":"float32","model_type":{"embedding":{"pooling":"cls"}},"max_concurrent_requests":512,"max_input_length":512,"max_batch_tokens":16384,"max_batch_requests":null,"max_client_batch_size":32,"tokenization_workers":10,"version":"0.6.0","sha":"5218224c4d6380897af937797b9a95df487bfba1","docker_label":null}
```

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```sh
text-embeddings-router --help
```

There is no --cors-allow-origin flag like showed in the README.

Also I have 2 machine in the same network with IPs:
- 172.16.129.1 <-- running TEI
- 172.16.129.136

When running with --hostname 0.0.0.0, it can not be reached by other machines in the same network. Within the same machine, I can check `curl 172.17.129.1:3000/info`. But from the machine `172.17.129.136`, I can not run `curl 172.17.129.1:3000/info`.

### Expected behavior

Flag `--cors-allow-origin` should work. And the router can be reached by other machines within the same network when binding to 0.0.0.0

**Comment by karlomikus** [comment]
Same problem here, but you can use ENV variable `CORS_ALLOW_ORIGIN`. Here's how I'm using it in docker:

``` yaml
environment:
      - CORS_ALLOW_ORIGIN=http://localhost:8080
```
