### ISSUE TITLE
Serving fine-tuned model from local directory

### ISSUE THREAD

**Issue by wdhitchc** [huggingface/text-embeddings-inference#116]
### Feature request

If I don’t want to upload my finetuned embedding models, Am I able to serve models that I have in a directory by mounting them into the container? 

### Motivation

The need to offer models that aren’t on the hugging face hub 

### Your contribution

Happy to work on a PR if someone can point me in the right direction.

**Comment by OlivierDehaene** [comment]
Yes this is already possible. Just provide the root directory of your model as a `--model-id`.

**Comment by caijijuhe** [comment]
Once the root directory of the model is provided as --model-id, it will still be downloaded from hf

**Comment by caijijuhe** [comment]
Still cannot use the local model
