### ISSUE TITLE
Add API token so we can have private endpoints

### ISSUE THREAD

**Issue by jpbalarini** [huggingface/text-embeddings-inference#118]
### Feature request

Create a secret token or password so that if it's set, any requests made to the API require the token/password.

### Motivation

I want to run a service that provides embeddings for my various applications. I want this to be publicly accessible, but only to the clients I want. 
Right now, if I put the service behind a public IP, anyone could use it to create embeddings (using resources and possibly overloading the server).

I suggest adding a secret token or password so that if set, it's required by the API.

### Your contribution

I don't know much Rust. I tried checking the code, but I couldn't figure out how to do this. Happy to help in anything I can

**Comment by OlivierDehaene** [comment]
This is out of scope of this project. If you need authentication, you need to add a layer on top of TEI.

**Comment by jpbalarini** [comment]
@OlivierDehaene, no worries. Do you have any recommendations or easy ways of doing that?

**Comment by OlivierDehaene** [comment]
Sure you can use NGINX for example: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/.
