### ISSUE TITLE
No tokenizer.json

### ISSUE THREAD

**Issue by DHOFM** [huggingface/text-embeddings-inference#122]
### System Info

if I try a hugging face model without tokenizer.json I get for example: client error (404 Not Found) for url (https://huggingface.co/T-Systems-onsite/german-roberta-sentence-transformer-v2/resolve/main/tokenizer.json)

so how to solve this? Do I need to load the model with transformers library, save the tokenizer.json and then load it locally or is there another way?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

docker run -p 8080:80 -v $volume:/data image here --model-id T-Systems-onsite/german-roberta-sentence-transformer-v2

### Expected behavior

load without need to store it

**Comment by OlivierDehaene** [comment]
Once you have the `tokenizer.json` locally, you can create a PR on the Hub and then use the revision (branch or commit) of this PR directly with the `--revision` arg.
