### ISSUE TITLE
Support `query_instruction`

### ISSUE THREAD

**Issue by xiaoxixxxx** [huggingface/text-embeddings-inference#124]
### Feature request

Hey, 

Are you currently supporting `query_instruction`  for [BAAI/bge-large-zh](https://huggingface.co/BAAI/bge-large-zh)?

```
model = HuggingFaceBgeEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
query_instruction="为这个句子生成表示以用于检索相关文章："
)
````

### Motivation

[BAAI/bge-large-zh](https://huggingface.co/BAAI/bge-large-zh)

### Your contribution

.

**Comment by OlivierDehaene** [comment]
To use query instruction, just concatenate the query instruction and the text you want to embed before sending it to the backend.
