### ISSUE TITLE
Batch grpc calls

### ISSUE THREAD

**Issue by RicardoHS** [huggingface/text-embeddings-inference#125]
### Feature request

When using the inference server with grpc it's not possible to batch multiple request on a single grpc call, only one by one. eg:

```
# this is possible
grpcurl -d '{"inputs": "What is Deep Learning"}' -plaintext 0.0.0.0:3000 tei.v1.Embed/Embed

# this is not
grpcurl -d '{"inputs": ["What is Deep Learning","kk","kk2"]}' -plaintext 0.0.0.0:3000 tei.v1.Embed/Embed
```

### Motivation

Using batching one could take advantage of batches when using GPU

### Your contribution

AFAIK this is easily achievable by changing the protobuf signature

**Comment by OlivierDehaene** [comment]
There is no real reason to batch in a true use case in my opinion. You can just open a stream and asynchronously send as many request as you want as soon as you can.

**Comment by RicardoHS** [comment]
It makes sense if using a GPU. The overhead when moving the data to VRAM is considerable.

I have tested a workload. Batching calls with 1024 items in HTTP takes ~30minutes, the same workload with gprc calling one by one takes 1h 21minutes.

I agree it makes no sense when using CPU but with GPU is prefered in most cases.

**Comment by OlivierDehaene** [comment]
TEI internally does not care if the requests were pushed as part of a batch or not: they are all pushed to an internal queue that is re-batched to the optimal size given a set of hyper-parameters. The batch endpoint exists for people to have somewhat good throughput when calling TEI in a single thread syncrhonously. 

Optimal throughput is not achieved this way anyways. TEI, like any high performance service, should be used asynchronously and with multiple threads. Grafana K6 has a lot of good resources on this if you want.

If you have a difference between the two, you are not pushing messages fast enough to the gRPC server. We have a benchmark in `load_tests/load_grpc_stream.js` that shows that gRPC is actually faster than the REST endpoint even with a single stream.

**Comment by fused-byte** [comment]
Hi @OlivierDehaene ,

Thanks for this wonderful library and responses above. Could you also help with, for how long TEI wait for re-batching before proceeding to process the requests if the max batch token or other criteria is not fulfilled?
