### ISSUE TITLE
Support SPLADE style sparse embeddings

### ISSUE THREAD

**Issue by jordanparker6** [huggingface/text-embeddings-inference#129]
### Feature request

It would be great to have a single server to calculate the dense / sparse embeddings fro hybrid search.

Having a sparse endpoint that would calculate the sparse embeddings would do this.

### Motivation

I want to be able to use the same TEI server for my dense and sparse embedding calculations with hybrid search.

### Your contribution

I am happy to help by working on a PR.

The following code from llama_index may be of use for processing the incoming vectors and returning it in a sparse format for dbs like Qdrant.

```py
def default_sparse_encoder(model_id: str) -> SparseEncoderCallable:
    try:
        import torch
        from transformers import AutoModelForMaskedLM, AutoTokenizer
    except ImportError:
        raise ImportError(
            "Could not import transformers library. "
            'Please install transformers with `pip install "transformers[torch]"`'
        )

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForMaskedLM.from_pretrained(model_id)
    if torch.cuda.is_available():
        model = model.to("cuda")

    def compute_vectors(texts: List[str]) -> Tuple[List[List[int]], List[List[float]]]:
        """
        Computes vectors from logits and attention mask using ReLU, log, and max operations.
        """
        # TODO: compute sparse vectors in batches if max length is exceeded
        tokens = tokenizer(
            texts, truncation=True, padding=True, max_length=512, return_tensors="pt"
        )
        if torch.cuda.is_available():
            tokens = tokens.to("cuda")

        output = model(**tokens)
        logits, attention_mask = output.logits, tokens.attention_mask
        relu_log = torch.log(1 + torch.relu(logits))
        weighted_log = relu_log * attention_mask.unsqueeze(-1)
        tvecs, _ = torch.max(weighted_log, dim=1)

        # extract the vectors that are non-zero and their indices
        indices = []
        vecs = []
        for batch in tvecs:
            indices.append(batch.nonzero(as_tuple=True)[0].tolist())
            vecs.append(batch[indices[-1]].tolist())

        return indices, vecs

    return compute_vectors
```

**Comment by OlivierDehaene** [comment]
Correct me if I'm wrong, but the SPLADE models are specific, right? So even once we add SPLADE support in TEI, you will still need to launch 2 replicas of TEI to serve both your SPLADE model and your embedding model.

**Comment by jordanparker6** [comment]
> Correct me if I'm wrong, but the SPLADE models are specific, right? So even once we add SPLADE support in TEI, you will still need to launch 2 replicas of TEI to serve both your SPLADE model and your embedding model.

Yeah sorry, just saw the comment about a single process per model. Its not that much of a hassle to run TEI on two different cloud run services, one for each model. 

A unified inference server for sparse and dense embeddings would be great, especially given the recent adoption by vector DBs like qdrant. Hybrid retrieval is getting a bit of attention in the RAG world.

I believe SPLADE has a different model for vectorising the document and vectorising the query so this is something to think about too. 

I beleive COLBERTv2 is also a sparse vector so there may be some overlap. I am not too familiar with COLBERT though.

**Comment by OlivierDehaene** [comment]
> A unified inference server for sparse and dense embeddings would be great

Yes, I think so too. I'm wondering on which route I will add this though. It could be supported in /embed as at the end of the day it returns an embedding too. But a new /embed_sparse could also be great to have a simplified API where only the nonzero elements are returned. 
For now, I'm leaning on keeping them behind /embed.

> I believe SPLADE has a different model for vectorising the document and vectorising the query so this is something to think about too.

Ok. This will be the responsability of the user to figure it out though.

**Comment by hiepxanh** [comment]
@jordanparker6  can you test new version
