### ISSUE TITLE
Gzip compression

### ISSUE THREAD

**Issue by snapshotpl** [huggingface/text-embeddings-inference#134]
### Feature request

Current apis (default and openai format) response with raw jsons. Many APIs have option to response with gzip, to improve amount of data and network traffic.

### Motivation

A lot of date fly in network. Adding gzip compression should improve API performance.

### Your contribution

I can help with code review, but I don't have any experience with Rust.

**Comment by OlivierDehaene** [comment]
I don't think the compression rate will be anything substantial on embeddings.
