### ISSUE TITLE
Different output between TEI and SentenceTransformer on text > 256 tokens

### ISSUE THREAD

**Issue by gerritvd** [huggingface/text-embeddings-inference#146]
### System Info

TEI v0.6

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

```
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer

st = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device='cpu')
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')

text = "Hello world, " * 3000
payload = text[:1100] # turns out to be 256 tokens
encoded_input = tokenizer(payload, padding=True, truncation=True, return_tensors='pt')
print(f"payload tokens: {len(encoded_input['input_ids'][0])}")
result1 = generate_tei("all-minilm-l6-v2-tei", payload, normalize=True, truncate=True)
result2 = st.encode([payload], normalize_embeddings=True)
cos_sim = cosine_similarity(result1, result2)
print(f"cosine sim: {cos_sim}")
```
The above will generate a cos sim of 0.99999742 and is exactly 256 tokens according to the tokenizer
When I replace the payload with:
```
payload = text[:1200]
```
cosine sim suddenly drops to **0.99138321**. Adding more tokens will significantly decrease the similarity, especially when text is used that is not as repetitive as the example provided.

### Expected behavior

cosine similarity would still be around **0.99999**

**Comment by OlivierDehaene** [comment]
I think it's because sentence transformers uses [this parameter](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/sentence_bert_config.json#L2), truncating to 256 tokens while TEI reads [this parameter](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/config.json#L14). 
So if you have more that 256 tokens the embeddings are different.

@tomaarsen, which one is the correct one?

**Comment by tomaarsen** [comment]
@OlivierDehaene 
The [`max_position_embeddings`](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/config.json#L14) refers to the maximum value that the base model can handle before crashing or falling in performance. The [`max_seq_length`](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/sentence_bert_config.json#L2) refers to the maximum value that the finetuned Sentence Transformer should recognize, anything above that should not be used.

The latter is used in Sentence Transformers to determine the `max_length` in the tokenizer.



---

@OlivierDehaene To implement this, you'll have to try and find the configuration file and read the `max_seq_length`. These are the possible filenames: https://github.com/UKPLab/sentence-transformers/blob/dbc0f16a7f6c6bd42a699bfda4bcaaed7c90b428/sentence_transformers/models/Transformer.py#L169-L177 

Nowadays, models are only pushed with `sentence_bert_config.json`, but a much older version also used those other config files.

Apologies for the inconvenience of this all, not all decisions that were made regarding ST back in the day were as well thought out.

- Tom Aarsen
