### ISSUE TITLE
why would the cpu-0.6 try to use gpu ?

### ISSUE THREAD

**Issue by garyng2000** [huggingface/text-embeddings-inference#149]
### System Info

docker image built for cpu

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I try the simplest command to start the cpu version as below

docker run --gpus all -p 8888:80 -v $volume:/data -d ghcr.io/huggingface/text-embeddings-inference:cpu-0.6 --model-id $model --revision $revision

but get error below
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

this is a machine without gpu card

### Expected behavior

it should start

**Comment by OlivierDehaene** [comment]
Remove `--gpus all` from the docker command.
