### ISSUE TITLE
Render Prometheus metrics for gRPC images

### ISSUE THREAD

**Issue by bruvduroiu** [huggingface/text-embeddings-inference#150]
### Feature request

Currently, the gRPC router only runs `install` on the the `metrics_exporter_prometheus::PrometheusBuilder`, and the TEI logs report:

```
2024-02-06T01:55:42.112898Z  INFO text_embeddings_router::grpc::server: router/src/grpc/server.rs:831: Serving Prometheus metrics: 0.0.0.0:9000
```

However, there is no handler handling the rendering of Prometheus metrics for requests to that endpoint.

Request: Using either a scrape endpoint or push gateway configuration, handle the rendering of Prometheus metrics for the gRPC images

### Motivation

Aligning features of HTTP TEI images and gRPC images.

Allowing TEI telemetry for users that are using gRPC images

### Your contribution

I could implement this feature with minimal guidance for the direction of the implementation (i.e. is it as simple as replicating the `prom_handler` in the HTTP server). I am not a Rust programmer, but willing to give it a shot

**Comment by OlivierDehaene** [comment]
> However, there is no handler handling the rendering of Prometheus metrics for requests to that endpoint.

What do you mean?

```shell
grpcurl -d '{"inputs": "What is Deep Learning"}' -plaintext 0.0.0.0:3000 tei.v1.Embed/Embed

curl 0.0.0.0:3000
```

gives you:

```
# TYPE te_embed_success counter
te_embed_success 1

# TYPE te_request_success counter
te_request_success{method="single"} 1

# TYPE te_embed_count counter
te_embed_count 1

# TYPE te_request_count counter
te_request_count{method="single"} 1

# TYPE te_queue_size gauge
te_queue_size 0

...
```

**Comment by bruvduroiu** [comment]
@OlivierDehaene thanks for providing this info, I must've been confused looking at the source code. Can you please help me understand how this endpoint should be queried?

Replicating your example above on `cpu-0.6-grpc`, a `curl` request to `0.0.0.0:3000` yields:

```
curl: (1) Received HTTP/0.9 when not allowed
```

Similarly, pointing a Prometheus scrape job to this endpoint fails (this is within docker-compose so `embeddings` is the DNS name of the TEI service, exposing port 8080)

```
  - job_name: "embeddings"
    scrape_interval: 5s
    static_configs:
      - targets: ["embeddings:8080"]
    metrics_path: "/"
```


```
ts=2024-02-06T16:22:14.834Z caller=scrape.go:1274 level=debug component="scrape manager" scrape_pool=embeddings target=http://embeddings:8080/ msg="Scrape failed" err="Get \"http://embeddings:8080/\": net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x12\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x04\\x00\\x10\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\\x00\\x06\\x01\\x00\\x00\\x00\""
```

Thank you very much!

**Comment by bruvduroiu** [comment]
Took another look after posting the comment and realised that with gRPC images, port 9000 needs to also be exposed for the HTTP Prometheus endpoint.

Finally, for:

```
$ docker run -d -p 8080:80 -p 9000:9000 -v $volume:/data --pull always ghcr.io/huggingface/text-embeddings-inference:0.6-grpc --model-id $model --revision $revision

$ grpcurl -d '{"inputs": "What is Deep Learning"}' -plaintext 0.0.0.0:3000 tei.v1.Embed/Embed

$ curl 0.0.0.0:9000

# TYPE te_embed_success counter
te_embed_success 1

# TYPE te_request_success counter
te_request_success{method="single"} 1

# TYPE te_embed_count counter
te_embed_count 1

# TYPE te_request_count counter
te_request_count{method="single"} 1

# TYPE te_queue_size gauge
te_queue_size 0
```

Let me know if you'd want me to contribute to the documentation in any way for this.
