### ISSUE TITLE
Add support for `nomic-ai/nomic-embed-text-v1`

### ISSUE THREAD

**Issue by ZQ-Dev8** [huggingface/text-embeddings-inference#152]
### Feature request

TEI currently does not appear to support nomic's newest embedding model: [nomic-ai/nomic-embed-text-v1](https://huggingface.co/nomic-ai/nomic-embed-text-v1). When attempting to load the model with docker image `ghcr.io/huggingface/text-embeddings-inference:latest` (sha-6395a7a), I receive the following error:
```
Error: Failed to parse `config.json`

Caused by:
    missing field `pad_token_id` at line 56 column 1
Failed to run text-embeddings-router.
```

### Motivation

`nomic-ai/nomic-embed-text-v1` is likely to be a popular open-source embedding model, given its position on the MTEB leaderboard and its enormous context window. Thus, support for this model in TEI would be of great benefit to the community.

### Your contribution

Given some general guidelines, I am willing to assist in preparing the model for TEI compatibility.

**Comment by OlivierDehaene** [comment]
nomic is definietly in my prio list but I have other things I need to tackle first.
Thanks for asking for it though as it's always good to know that the community is interested in something to correclty set the priorities for the repo.

**Comment by MaheshNat** [comment]
+1
