### ISSUE TITLE
Add support for intfloat/multilingual-e5-large-instruct

### ISSUE THREAD

**Issue by katopz** [huggingface/text-embeddings-inference#153]
### Feature request

Support https://huggingface.co/intfloat/multilingual-e5-large-instruct/tree/main

### Motivation

We already support [intfloat/multilingual-e5-large](https://hf.co/intfloat/multilingual-e5-large) but seem to break with `intfloat/multilingual-e5-large-instruct`

```
Error: The `--pooling` arg is not set and we could not find a pooling configuration (`1_Pooling/config.json`) for this model.

Caused by:
    No such file or directory (os error 2)
```

### Your contribution

-

**Comment by OlivierDehaene** [comment]
That's because the model is not in a sentence transformers compatible format. Just had `--pooling mean`.
