### ISSUE TITLE
/rerank description in API documentation

### ISSUE THREAD

**Issue by spttt** [huggingface/text-embeddings-inference#159]
I'm confused about a description in the documentation.
Is the description of /rerank in the documentation wrong? It is described as "Returns a 424 status code if the model is not a **Sequence Classification model** with a single class."
Why not write it as “… if the model is not a **Re-Ranking model** ”

https://github.com/huggingface/text-embeddings-inference/blob/a059696a33f3b2cd28ce5e69d3195d5b03189d96/docs/openapi.json#L357C1-L359C1

**Comment by OlivierDehaene** [comment]
A re-ranking model is a sequence classification model with a single class. That's how we detect them in the code.
