### ISSUE TITLE
504 Error for bge-base-en-v1.5

### ISSUE THREAD

**Issue by shoang22** [huggingface/text-embeddings-inference#165]
### System Info

I'm getting a 504 error when using bge with longer docs. Is there some way to modify the timeout length?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

POST request using /embed endpoint

### Expected behavior

Generate embeddings

**Comment by OlivierDehaene** [comment]
504 is on the client side. You need to increase the timeout in your HTTP client.

**Comment by OlivierDehaene** [comment]
TEI does not return 504s. Maybe you have a proxy in the middle?
