### ISSUE TITLE
Is there a python package for this?

### ISSUE THREAD

**Issue by mspronesti** [huggingface/text-embeddings-inference#17]
### Feature request

Hi there, awesome work as usual!
I was just wondering if you are planning to package a Python API for this library.

### Your contribution
I could contribute to this if planned.

**Comment by OlivierDehaene** [comment]
Yes you can use the official `huggingface-hub` package.
For example:

```shell
pip install huggingface-hub
```

```python
from huggingface_hub import InferenceClient

client = InferenceClient()
client.feature_extraction("What is deep learning?", model="http://localhost:3000")
```
