### ISSUE TITLE
Best Practices for Deploying Multiple Models for Improved Concurrency

### ISSUE THREAD

**Issue by zhanghx0905** [huggingface/text-embeddings-inference#177]
### Feature request

Hello,

I'm currently working on deploying the text-embeddings-inference model in a production environment. A single instance of the model often isn't sufficient to handle the volume of requests.

I'm considering deploying multiple instances of the model and implementing a request scheduling mechanism among them to better manage the load. I'd like to gather insights or recommendations on the best practices for such a setup.

### Motivation

...

### Your contribution

...

**Comment by OlivierDehaene** [comment]
You can have a look at this answer for a basic setup using nginx: https://github.com/huggingface/text-embeddings-inference/issues/87#issuecomment-1822970062
