### ISSUE TITLE
How to specify a local model

### ISSUE THREAD

**Issue by yuanjie-ai** [huggingface/text-embeddings-inference#178]
### Feature request

model=BAAI/bge-reranker-large
volume=$PWD/data
docker run -p 8080:80 -v $volume:/data --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-1.0 --model-id $model

### Motivation

model=BAAI/bge-reranker-large
volume=$PWD/data
docker run -p 8080:80 -v $volume:/data --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-1.0 --model-id $model

### Your contribution

null

**Comment by OlivierDehaene** [comment]
Use a local directory as `--model-id`.
If you are running in docker you need to mount the directory to the container first with `--volume`.
