### ISSUE TITLE
M chip Metal GPU support

### ISSUE THREAD

**Issue by theskcd** [huggingface/text-embeddings-inference#18]
### Feature request

I might be missing something, but on the M chip based macbook is it possible to force the crate to use the GPU instead of the CPU (the GPU would be much faster for generating embeddings).

### Motivation

We are  running a rust binary locally on the user device, and often they use macbooks, the tokenization is part of the slowest step. I would love to use the M chip GPU where possible.

### Your contribution

Happy to put in PRs to make this happen 🪄

**Comment by OlivierDehaene** [comment]
For now Candle does not support Metal (macOS driver for GPU) so that's not possible yet. 
This is one of our focus right now.

**Comment by theskcd** [comment]
MVP energy! I will wait for you guys to ship it. In the meanwhile do let me know if there is a beta build or anything of that sort I can try out. Happy to provide feedback and help out in anyway.
