### ISSUE TITLE
Is aarch64 linux supported?

### ISSUE THREAD

**Issue by lkyhfx** [huggingface/text-embeddings-inference#19]
Is aarch64 Linux supported? Or, if aarch64 Linux benefits from this project, how does it compare to transformers?

**Comment by OlivierDehaene** [comment]
> Is aarch64 Linux supported?

It should be I have not tried.

> if aarch64 Linux benefits from this project, how does it compare to transformers?

What do you mean? How is the arch of your CPU related to transformers or this project?

**Comment by dnabanita7** [comment]
No, aarch64 linux not supported. I tried that using docker.

**Comment by OlivierDehaene** [comment]
Well yes the docker target is x86. But you can try to compile from source/build your own container and it should work.

**Comment by lkyhfx** [comment]
Thanks for the reply. Sorry for the uncleanliness; I thought TEI used some CPU architecture-specific features to improve performance. I will try to build an aarch64 Linux Docker image on my own.

**Comment by OlivierDehaene** [comment]
> I thought TEI used some CPU architecture-specific features to improve performance.

Candle does indeed and it should support arm. If it does not, we will add it so please report back.
