### ISSUE TITLE
Is it possible to use the local model directly without downloading it?

### ISSUE THREAD

**Issue by CharleyXu** [huggingface/text-embeddings-inference#207]
### Feature request

When deploying using docker, can I use the local model directly without downloading it?

### Motivation

When I deploy using docker, the model download fails.
```Java
2024-03-20T03:24:40.668716930Z 2024-03-20T03:24:40.668186Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:20: Starting download
2024-03-20T03:25:55.700406269Z Error: Could not download model artifacts
2024-03-20T03:25:55.700473367Z
2024-03-20T03:25:55.700493788Z Caused by:
2024-03-20T03:25:55.700500052Z     0: request error: error sending request for url (https://huggingface.co/BAAI/bge-large-zh-v1.5/resolve/refs%2Fpr%2F13/config.json): error trying to connect: tcp connect error: Connection refused (os error 111)
2024-03-20T03:25:55.700504184Z     1: error sending request for url (https://huggingface.co/BAAI/bge-large-zh-v1.5/resolve/refs%2Fpr%2F13/config.json): error trying to connect: tcp connect error: Connection refused (os error 111)
2024-03-20T03:25:55.700507728Z     2: error trying to connect: tcp connect error: Connection refused (os error 111)
2024-03-20T03:25:55.700511094Z     3: tcp connect error: Connection refused (os error 111)
2024-03-20T03:25:55.700514310Z     4: Connection refused (os error 111)
```

### Your contribution

by submitting a PR

**Comment by CharleyXu** [comment]
i get it.

**Comment by ruifengma** [comment]
same question. Is this solved? @CharleyXu

**Comment by CharleyXu** [comment]
> same question. Is this solved? @CharleyXu

Yes, it's solved.

**Comment by CharleyXu** [comment]
> @CharleyXu do you know why you fail to connect to the hub? I think #216 has the same issue.

It is estimated that the address [huggingface.co](huggingface.co ) not accessible. When the model is not loaded locally, it will try to download the model.

**Comment by wanzhixiao** [comment]
> > same question. Is this solved? @CharleyXu
> 
> Yes, it's solved. If you download the 'bge-reranker-base' model from Hugging Face to the local directory 'data', execute the Docker command.
> 
> ```shell
> model="./data/bge-reranker-base" && volume="$PWD/data" && docker run -p 9003:9003 -v $volume:/data -e PORT=9003 --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-1.1 --model-id $model
> ```

I tried this command and it still report error, i guess the linux server can't connect huggingface hub?

```shell
model="/data/pretrain_model/bge-small-zh-v1.5" && volume="$PWD/data" && docker run --gpus all -p 9003:80 -v $volume:/data -e PORT=9003 --pull always ghcr.io/huggingface/text-embeddings-inference:86-0.6 --model-id $model
```

```shell
86-0.6: Pulling from huggingface/text-embeddings-inference
Digest: sha256:95303394a60d25603ffd5518b8c9d78a0e59e82e232c1cff335e0635c9293627
Status: Image is up to date for ghcr.io/huggingface/text-embeddings-inference:86-0.6
2024-03-29T02:37:00.838117Z  INFO text_embeddings_router: router/src/main.rs:112: Args { model_id: "/dat*/********_*****/***-*****-**-v1.5", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, hf_api_token: None, hostname: "b47dd949858a", port: 9003, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: Some("/data"), json_output: false, otlp_endpoint: None }
2024-03-29T02:37:00.838360Z  INFO hf_hub: /root/.cargo/git/checkouts/hf-hub-1aadb4c6e2cbe1ba/b167f69/src/lib.rs:55: Token file not found "/root/.cache/huggingface/token"    
2024-03-29T02:39:08.168038Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:9: Starting download
Error: Could not download model artifacts

Caused by:
    0: request error: error sending request for url (https://huggingface.co//data/pretrain_model/bge-small-zh-v1.5/resolve/main/config.json): error trying to connect: tcp connect error: Connection timed out (os error 110)
    1: error sending request for url (https://huggingface.co//data/pretrain_model/bge-small-zh-v1.5/resolve/main/config.json): error trying to connect: tcp connect error: Connection timed out (os error 110)
    2: error trying to connect: tcp connect error: Connection timed out (os error 110)
    3: tcp connect error: Connection timed out (os error 110)
    4: Connection timed out (os error 110)
```

**Comment by CharleyXu** [comment]
> > > same question. Is this solved? @CharleyXu
> > 
> > 
> > Yes, it's solved. If you download the 'bge-reranker-base' model from Hugging Face to the local directory 'data', execute the Docker command.
> > ```shell
> > model="./data/bge-reranker-base" && volume="$PWD/data" && docker run -p 9003:9003 -v $volume:/data -e PORT=9003 --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-1.1 --model-id $model
> > ```
> 
> I tried this command and it still report error, i guess the linux server can't connect huggingface hub?
> 
> ```shell
> model="/data/pretrain_model/bge-small-zh-v1.5" && volume="$PWD/data" && docker run --gpus all -p 9003:80 -v $volume:/data -e PORT=9003 --pull always ghcr.io/huggingface/text-embeddings-inference:86-0.6 --model-id $model
> ```
> 
> ```shell
> 86-0.6: Pulling from huggingface/text-embeddings-inference
> Digest: sha256:95303394a60d25603ffd5518b8c9d78a0e59e82e232c1cff335e0635c9293627
> Status: Image is up to date for ghcr.io/huggingface/text-embeddings-inference:86-0.6
> 2024-03-29T02:37:00.838117Z  INFO text_embeddings_router: router/src/main.rs:112: Args { model_id: "/dat*/********_*****/***-*****-**-v1.5", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, hf_api_token: None, hostname: "b47dd949858a", port: 9003, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: Some("/data"), json_output: false, otlp_endpoint: None }
> 2024-03-29T02:37:00.838360Z  INFO hf_hub: /root/.cargo/git/checkouts/hf-hub-1aadb4c6e2cbe1ba/b167f69/src/lib.rs:55: Token file not found "/root/.cache/huggingface/token"    
> 2024-03-29T02:39:08.168038Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:9: Starting download
> Error: Could not download model artifacts
> 
> Caused by:
>     0: request error: error sending request for url (https://huggingface.co//data/pretrain_model/bge-small-zh-v1.5/resolve/main/config.json): error trying to connect: tcp connect error: Connection timed out (os error 110)
>     1: error sending request for url (https://huggingface.co//data/pretrain_model/bge-small-zh-v1.5/resolve/main/config.json): error trying to connect: tcp connect error: Connection timed out (os error 110)
>     2: error trying to connect: tcp connect error: Connection timed out (os error 110)
>     3: tcp connect error: Connection timed out (os error 110)
>     4: Connection timed out (os error 110)
> ```
Follow my example to test validation. The model path is incorrect

**Comment by wanzhixiao** [comment]
> ```shell
> model="./data/bge-reranker-base" 
> ```

do you mean 
model="./data/bge-reranker-base" ,    should i use the relative path rather than absolute path?

**Comment by wanzhixiao** [comment]
> > ```shell
> > model="./data/bge-reranker-base" ; model="/data/pretrain_model/bge-small-zh-v1.5"
> > ```
> 
> do you mean model="./data/bge-reranker-base" , should i use the relative path rather than absolute path?

I run this command and it success! the port is 9003 not 8080
model="./data/bge-small-zh-v1.5" && volume="$PWD/data" && docker run --gpus all -p 9003:9003 -v $volume:/data -e PORT=9003 --pull always ghcr.io/huggingface/text-embeddings-inference:86-0.6 --model-id $model

**Comment by 3252152** [comment]
Reminder to everyone, model id must use relative paths
