### ISSUE TITLE
Incorrect URL for OpenAI compatibility (missing /v1)

### ISSUE THREAD

**Issue by matatonic** [huggingface/text-embeddings-inference#213]
### System Info

N/A

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

By setting the OPENAI_BASE_URL environment variable to: "http://\<server ip\>:\<port\>/v1" and using this API with the openai client, results in 404. See here for how OpenAI expects the base_url to be used: https://github.com/openai/openai-python/blob/5cfb125acce0e8304d12bdd39b405071021db658/src/openai/_client.py#L110
```
        if base_url is None:
            base_url = os.environ.get("OPENAI_BASE_URL")
        if base_url is None:
            base_url = f"https://api.openai.com/v1"
```

So, the /embeddings API endpoint should be changed to /v1/embeddings (or at least added as an alias for any unfortunate clients who have implemented workarounds for the incorrect path).

test code:
```python
import openai

#client = openai.Client(base_url="http://localhost:80") # works with text-embeddings-inference
client = openai.Client(base_url="http://localhost:80/v1") # 404, correct usage
emb = client.embeddings.create(input=['this is a 404'], model="text-embeddings-latest")
print(emb)
```

### Expected behavior

not 404

**Comment by OlivierDehaene** [comment]
#112
