### ISSUE TITLE
Truncate automatically for the embeddings endpoint

### ISSUE THREAD

**Issue by SeEngel** [huggingface/text-embeddings-inference#218]
### System Info

I would like to suggest an important improvement for the "text-embedding-inference" repository, specifically for the "embeddings" endpoint.

Currently, the endpoint calculates text embeddings based on the input tokens. However, when the number of tokens in a given sentence exceeds the maximum token limit, the endpoint sends a error back to the user, e.g. "Input validation error: `inputs` must have less than 512 tokens. Given: 527". This make it difficult for users to find the right number of words or cutting point in a given sentence.

To improve user experience and ensure better transparency, I propose adding a warning mechanism to the "embeddings" endpoint replacing the error and returning the embedding based on the truncated sentence. This would notify users when their input sentences are truncated due to the maximum token limit being reached. However, the endpoint can still have the openai compatible form.

Thank you for considering this suggestion. I am looking forward to your feedback and the potential implementation of this feature.

Best regards,

Sebastian

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

curl -X 'POST' \
  'https://0.0.0.0/v1/embeddings' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model": "bge-large-en-v1.5",
  "input": [
"Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various indsSure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various indsSure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various indsSure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various industries Sure, Id be happy to help you generate a text of around 500 words. Here is an example of a text on the topic of 5G technology and its potential impact on various inds"
  ],
  "user": "string"
}'

Error Message:

{
  "message": "Input validation error: `inputs` must have less than 512 tokens. Given: 598",
  "code": 413,
  "type": "Validation"
}

### Expected behavior

Here are some possible solutions:

- Return a warning message in the API response, indicating that the input sentence was truncated and how many tokens were retained.

**Comment by SeEngel** [comment]
Hi, a header is a flag I have to set when executing "text-embeddings-router"?
However, any possibility to set a truncation without enforcing the user to
calculate the right number of words would be very helpful.

Thank you very much, your

Sebastian Engel

OlivierDehaene ***@***.***> schrieb am Mi., 27. März 2024,
12:03:

**Comment by SeEngel** [comment]
Hi, thank you very much for the implementation. However, i still have the same tuncation error when i set the auto-truncate flag. I.e. i have used the following command to start the embedding application (i.e. used --auto-truncate):

text-embeddings-router --port 3000 --tokenization-workers 8 --auto-truncate --pooling cls --model-id WhereIsAI/UAE-Large-V1 --revision cf14327dbfe6270e4f6feb5fd0f436d85f90c4cc

The service starts and when i use the "v1/embeddings" endpoint i still get the token size error as described above.

Error:
{
  "message": "Input validation error: `inputs` must have less than 512 tokens. Given: 1038",
  "code": 413,
  "type": "Validation"
}

For the request (to v1/embeddings):

{
  "input": "string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strinstring strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin string strin strin strinstrinstrin strin strin",
  "model": "WhereIsAI/UAE-Large-V1",
  "user": "null"
}

**Comment by OlivierDehaene** [comment]
Oh yes I went a bit too fast my bad.

**Comment by SeEngel** [comment]
Hi, Thank you very much :)

Am Do., 4. Apr. 2024 um 10:35 Uhr schrieb OlivierDehaene <
***@***.***>:
