### ISSUE TITLE
Add binary & scalar embedding quantization support to text-embeddings-inference

### ISSUE THREAD

**Issue by dongxiaolong** [huggingface/text-embeddings-inference#219]
### Feature request

binary and scalar (int8) embedding quantization, which can be used with some embedding models to shrink the size of the (corpus) embeddings for retrieval. This results in notable reductions in index size/memory usage for the retrieval, as well as notable improvements in retrieval speed.
[Add binary & scalar embedding quantization support to Sentence Transformers ](https://github.com/UKPLab/sentence-transformers/pull/2549)

### Motivation

[Add binary & scalar embedding quantization support to Sentence Transformers ](https://github.com/UKPLab/sentence-transformers/pull/2549)
[Binary and Scalar Embedding Quantization for Significantly Faster & Cheaper Retrieval](https://huggingface.co/blog/embedding-quantization)

### Your contribution

None

**Comment by dongxiaolong** [comment]
#https://github.com/UKPLab/sentence-transformers/pull/2549

**Comment by dongxiaolong** [comment]
https://github.com/UKPLab/sentence-transformers/pull/2549

**Comment by OlivierDehaene** [comment]
This should be done client-side: TEI would always answer in float32 and the client can then run their own quantization strategy before addint the embeddings to their vector db.

**Comment by dongxiaolong** [comment]
> This should be done client-side: TEI would always answer in float32 and the client can then run their own quantization strategy before addint the embeddings to their vector db.

Thank you for your response; I believe you meant more appropriate for, example, vector database clients.
Such like:
[BinaryVectorDB](https://github.com/cohere-ai/BinaryVectorDB)
