### ISSUE TITLE
Classify pairs of strings

### ISSUE THREAD

**Issue by mhillebrand** [huggingface/text-embeddings-inference#223]
### Feature request

I have a fine-tuned DistilRoberta classifier that accepts a pair of strings and outputs a 0 or 1. When I try to use the TEI gRPC Docker image for this, I receive an error:

```
Traceback (most recent call last):
  File "/opt/classifier/client.py", line 40, in <module>
    result = client.predict([string1, string2])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/classifier/client.py", line 19, in predict
    request = tei_v1_pb2.PredictRequest(inputs=inputs, truncate=truncate, raw_scores=raw_scores)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad argument type for built-in operation
```

### Motivation

I'm trying to optimize all my classifiers, not just the ones that classify single strings.

### Your contribution

I could look into solving this issue—unless I'm just doing something dumb and no PR is needed.

**Comment by OlivierDehaene** [comment]
I added the PredictPair methods to cover this.
