### ISSUE TITLE
Perhaps it can tell us how Telemetry can be used locally, or set a local log storage address

### ISSUE THREAD

**Issue by Night-Quiet** [huggingface/text-embeddings-inference#226]
### Feature request

Telemetry may be a bit of a hurdle for ordinary people, I just want to monitor the running status of the model so that I can detect errors when they occur Or simply calculate the total time consumption to analyze communication and API time consumption

### Motivation

just hope to have a log file or indicate the use of remote sensing. Thank you.

### Your contribution

I'm sorry I can't provide any help

**Comment by OlivierDehaene** [comment]
>  I just want to monitor the running status of the model so that I can detect errors when they occur

Can't you already do that client-side? Errors can just be detected by checking the http code in the response right?

> Or simply calculate the total time consumption to analyze communication and API time consumption

I'm sorry I am not sure I understand what you describe here.

**Comment by Night-Quiet** [comment]
I'm sorry I didn't explain it clearly. I just want to obtain this information:
![b3aa158652337505bf6a2c004c0792a](https://github.com/huggingface/text-embeddings-inference/assets/73934131/8bdc6f5c-c378-40f6-a7f2-a89920233ac9)
Based on this information, coordinate with the client to calculate the API time and computation time.
The client-side can indeed detect errors through HTTP response codes, but I hope to monitor them through the server.
Thank you.

**Comment by lvliang-intel** [comment]
@OlivierDehaene, 
Is it possible to provide TEI Grafana Dashboard json file like TGI did?

Thanks.
