### ISSUE TITLE
Question: How to add a prefix to the underlying server

### ISSUE THREAD

**Issue by Ryojikn** [huggingface/text-embeddings-inference#229]
I've managed to run the text embeddings inference perfectly using the already built docker images and I'm trying to allow it to our internal components

Right now they're sharing the following behavior

Myhost.com/modelname/v1/embeddings

I was wondering if this "model name" is possible to add as a prefix inside the application through some configuration.

How could I do that?

**Comment by OlivierDehaene** [comment]
It's not possible with TEI directly.
You need to add a routing layer like NGINX, Pingora...
