### ISSUE TITLE
Docker image bloat

### ISSUE THREAD

**Issue by cheburakshu** [huggingface/text-embeddings-inference#252]
### System Info

the router is just ~8MB whereas the image is 1GB. Can this be fixed and released as a truly production-ready docker image?

```
ghcr.io/huggingface/text-embeddings-inference   1.2.2      940f548a1c90   8 days ago      1.02GB
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

list: docker images

### Expected behavior

no bloat, just few MB binary

**Comment by OlivierDehaene** [comment]
> the router is just ~8MB

It's not ? Where do you get this from?

**Comment by cheburakshu** [comment]
Just followed your instructions in documentation. You don't recognize your repo and image?

**Comment by cheburakshu** [comment]
ok to clarify, 1 GB is the minimal image that was advertised in the readme?

> Efficient Resource Utilization: Benefit from small Docker images and rapid boot times, allowing for true serverless capabilities.

**Comment by cheburakshu** [comment]
sorry it is 747 MB. may bad
