### ISSUE TITLE
Why two batching_task are Required?

### ISSUE THREAD

**Issue by sulude** [huggingface/text-embeddings-inference#253]
### Feature request

In the concurrent scenario, I tried to reduce a batching_task, and the batchsize of each embed is larger, so that the inference performance is better.In the single-concurrency scenario, the performance does not decrease.

### Motivation

Improves inference performance in concurrent scenarios.

### Your contribution

Only one batching_task is required.

**Comment by sulude** [comment]
![image](https://github.com/huggingface/text-embeddings-inference/assets/168315744/e4d575d0-e94a-4382-8ff7-689299ab6e0b)

**Comment by OlivierDehaene** [comment]
We use two batching tasks to prefetch.
This could be removed by allowing to move the backend to move the tensors to the device asynchronously but this is a simple workaround.
