### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by onel** [huggingface/text-embeddings-inference#255]
### Feature request

The repo should add a CONTRIBUTING.md

### Motivation

To help new contributors

### Your contribution

I can help with adding one if there is a widely used template
For example: https://github.com/huggingface/datasets/blob/main/CONTRIBUTING.md

**Comment by vrdn-23** [comment]
+1 for this

**Comment by OlivierDehaene** [comment]
Fixed by #291
