### ISSUE TITLE
Multiple Model Endpoint support

### ISSUE THREAD

**Issue by ruifengma** [huggingface/text-embeddings-inference#256]
### Feature request

Hello, My question is that if/how we support multiple models selection by a single api endpoint. For example, I have gte, bge etc. and I can deploy them together with the same url and switch easily among these model?

### Motivation

support multiple models

### Your contribution

Something like the fastchat controller register

**Comment by OlivierDehaene** [comment]
I don't think that's something we want to do in this repo:
- If you have enough requests per second, you will saturate the GPU with one model. Adding other models on the same GPU will only slow things down
- It is already easy to launch multiple processes of TEI on the same GPU and add a routing layer on top of it

For example:

```shell
volume=$PWD/data

# Create a network that the containers will share
docker network create tei-net

# Start 2 models on the same GPU in detach mode

docker run --gpus '"device=0"' --net tei-net --name tei-uae -v $volume:/data --pull always --rm -d ghcr.io/huggingface/text-embeddings-inference:1.2 --model-id WhereIsAI/UAE-Large-V1
docker run --gpus '"device=0"' --net tei-net --name tei-mxbai -v $volume:/data --pull always --rm -d ghcr.io/huggingface/text-embeddings-inference:1.2 --model-id mixedbread-ai/mxbai-embed-large-v1

# Create nginx.conf file

tee -a nginx.conf <<EOF
upstream uae {
    server tei-uae;
}

upstream mxbai {
    server tei-mxbai;
}
    
server {
    location /uae {
        proxy_pass http://tei-uae/;
    }
    location /mxbai {
        proxy_pass http://tei-mxbai/;
    }
}
EOF

# Start nginx container
docker run -v $PWD/nginx.conf:/etc/nginx/conf.d/default.conf:ro  -p 8080:80 --net tei-net nginx

# Curl first model
curl 127.0.0.1:8080/uae     -X POST     -d '{"inputs":"What is Deep Learning?"}'     -H 'Content-Type: application/json'

# Curl second model
curl 127.0.0.1:8080/mxbai     -X POST     -d '{"inputs":"What is Deep Learning?"}'     -H 'Content-Type: application/json'
```

**Comment by Jeadie** [comment]
Without being able to load multiple models in a single instance, TEI cannot be used as an OpenAI compatible embedding server.

**Comment by qdrddr** [comment]
Infinity supports running multiple models, and I think TEI should too.
