### ISSUE TITLE
Download the model at build time (not run time)

### ISSUE THREAD

**Issue by medievalCode** [huggingface/text-embeddings-inference#259]
### Feature request

I'm curious about whether we can obtain the model during the image build process. For instance, if we utilize arguments in the Dockerfile, we could use those to download the model and save it in the `data` directory. Then, when the Docker container is launched using `docker run`, it would be ready to serve immediately.

### Motivation

To manage models in a Kubernetes cluster, we must be able to dynamically adjust the number of pods based on request volume. Deploying replicas becomes time-consuming if each one needs to retrieve the model due to lack of access to a managed volume. A practical solution is to include the model directly within the Docker containers. This approach speeds up the deployment of new pods significantly.

### Your contribution

...

**Comment by somehowchris** [comment]
I'm not with the HuggingFace Team, but I had the same thought a few days ago. I totally get where you're coming from, but I don't think it's really possible to do this "agnostic" approach. The purpose of the interface is to have the option to choose what model to serve, and let's face it, some of these "modern" models are huge! Not even including private/gated models. For the same reason it would be impractical to build thousands of docker images.

Just some thoughts: k8s has RWX volumes, so this could be used to first download it via a job and then serve the models within deployments. If volumes aren't feasible, one would just need to create a Dockerfile extending the one, running some `huggingface-cli` download command, putting the model into `/data` as per the basic docker example. Push that to a private registry, and you're ready to deploy! I don't think either of these solutions will be any faster or slower than using the TEI as it is, unless your network is the bottleneck (which it often is).

**Comment by OlivierDehaene** [comment]
Bundling the model inside the image should be avoided:
- you need to create and maintain a lot of images
- your image registry becomes the bottleneck instad of Huggingface's CDN
