### ISSUE TITLE
Input validation error: `inputs` must have less than 512 tokens. Given: 551

### ISSUE THREAD

**Issue by abhipn** [huggingface/text-embeddings-inference#27]
This is the docker command I used to deploy the embedding model,

- `docker run -d --gpus all -p 8081:80 -v $volume:$PWD/data --pull always ghcr.io/huggingface/text-embeddings-inference:latest --model-id "BAAI/bge-large-en-v1.5"`

Now I tried sending a long text I'm getting below error, is truncation strategy disabled by default?

- `text_embeddings_core::infer: core/src/infer.rs:83: Input validation error: `inputs` must have less than 512 tokens. Given: 551`

Documentation was not much clear on handling this, any suggestions for this problem. 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

**Comment by OlivierDehaene** [comment]
You can provide the set the `truncate` argument to true in the payload to automatically truncate right the inputs.

```shell
curl 127.0.0.1:8080/embed \
    -X POST \
    -d '{"inputs":"What is Deep Learning?", "truncate": true}' \
    -H 'Content-Type: application/json'
```
See https://huggingface.github.io/text-embeddings-inference/#/Text%20Embeddings%20Inference/embed

**Comment by abhipn** [comment]
> You can set the `truncate` argument to true in the payload to automatically "truncate right" the inputs.
> 
> ```shell
> curl 127.0.0.1:8080/embed \
>     -X POST \
>     -d '{"inputs":"What is Deep Learning?", "truncate": true}' \
>     -H 'Content-Type: application/json'
> ```
> 
> See https://huggingface.github.io/text-embeddings-inference/#/Text%20Embeddings%20Inference/embed

Is it possible to change `max_input_length>512` and chunk the long document (i.e., >512 tokens) and then take a avg pooling to create a new embedding to support longer document? Is this support added internally?

**Comment by OlivierDehaene** [comment]
That's an interesting idea. Could you open a feature request detailing it?

**Comment by FarisHijazi** [comment]
any news on this feature?

**Comment by OlivierDehaene** [comment]
After thinking about it and sharing internally, I don't think it's a good feature: it will be very hard to decide on a default chunking strategy.

I think it's better if this is done client side.
See this great blog post: https://www.pinecone.io/learn/chunking-strategies/
