### ISSUE TITLE
Support for jinaai/jina-embeddings-v2-base-code

### ISSUE THREAD

**Issue by m-truscott** [huggingface/text-embeddings-inference#270]
### Model description

jina-embeddings-v2-base-code is an multilingual embedding model speaks English and 30 widely used programming languages. Same as other jina-embeddings-v2 series, it supports 8192 sequence length.

jina-embeddings-v2-base-code is based on a Bert architecture (JinaBert) that supports the symmetric bidirectional variant of [ALiBi](https://arxiv.org/abs/2108.12409) to allow longer sequence length. The backbone jina-bert-v2-base-code is pretrained on the [github-code](https://huggingface.co/datasets/codeparrot/github-code) dataset. The model is further trained on Jina AI's collection of more than 150 millions of coding question answer and docstring source code pairs. These pairs were obtained from various domains and were carefully selected through a thorough cleaning process.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

huggingface page: [jina-embeddings-v2-base-code](https://huggingface.co/jinaai/jina-embeddings-v2-base-code)

Also refer to [#44 ](https://github.com/huggingface/text-embeddings-inference/issues/44)

**Comment by cdxker** [comment]
:+1:  To this. Very important for our team as well

**Comment by slyt** [comment]
TEI works with jina-v2. I've been using it since October 2023.
