### ISSUE TITLE
very high cadinality metrics

### ISSUE THREAD

**Issue by deepakdeore2004** [huggingface/text-embeddings-inference#271]
### System Info

tei version is `v.0.6.0` 

there are 100k series for `te_batch_next_tokens_bucket` metric

<img width="505" alt="image" src="https://github.com/huggingface/text-embeddings-inference/assets/313430/1fbd5d41-5892-4435-9a28-c3a2aca3d3d1">

`le` shows 1697, 1660, 1696 and so on values, there should be very few buckets, looks like some bug related to this metric alone

rest metrics have very few series

uploaded metrics output
[m.gz](https://github.com/huggingface/text-embeddings-inference/files/15376999/m.gz)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

1. deploy huggingface/text-embeddings-inference:0.6
2. scrape metrics from prometheus/ or curl and grep for `te_batch_next_tokens_bucket` count

### Expected behavior

there should be very few number of metrics instead of 100k

**Comment by infa-nang** [comment]
> fix: limit the number of buckets for prom metrics by @OlivierDehaene in https://github.com/huggingface/text-embeddings-inference/pull/114

this is fixed as part of the release [v1.0.0](https://github.com/huggingface/text-embeddings-inference/releases/tag/v1.0.0)

**Comment by deepakdeore2004** [comment]
thanks @infa-nang
