### ISSUE TITLE
Inference error when passing long text with truncate enabled

### ISSUE THREAD

**Issue by andreaponti5** [huggingface/text-embeddings-inference#28]
### System Info

This is the docker command I used to deploy the embedding model:

```bash
docker run -p 8080:80 -v $volume:$PWD/data --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-latest --model-id intfloat/multilingual-e5-large
```

I tried to send a long text, setting the `truncate` parameter to `true` and I'm getting the following error:

`Backend error: Inference error: index-select invalid index 514 with dim size 514`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```python
import requests

body = {'inputs': 'Test text' * 1000, 'truncate': True}
res = requests.post('http://127.0.0.1/embed', json=body)
```

### Expected behavior

The response code should be `200` and the embedding of the truncated `inputs` should be returned.

Instead, the response code is `424` with the following error message: `Backend error: Inference error: index-select invalid index 514 with dim size 514`

**Comment by OlivierDehaene** [comment]
Fixed by https://github.com/huggingface/text-embeddings-inference/commit/aec5efd77ee25ed3d6282eba1a51bae134c4815b.
