### ISSUE TITLE
Too much cpu memory consumption

### ISSUE THREAD

**Issue by frankxyy** [huggingface/text-embeddings-inference#280]
Hi，I loaded bge-reranker-v2-m3 model and this consumed about 1.5G gpu memory. However, the cpu memory consumption is 11G. Why is it so large?

**Comment by frankxyy** [comment]
This is the machine stats checked by TOP

<img width="928" alt="image" src="https://github.com/huggingface/text-embeddings-inference/assets/6971044/8ee83cef-1ea3-4fc1-b110-4d491d487bd8">

**Comment by OlivierDehaene** [comment]
It depends on the size of the tokenizer. By default, we spawn one tokenizer per cpu core. If this tokenizer is big (because it's converted from sentencepiece for example), TEI can end up using a lot of RAM.
