### ISSUE TITLE
Support NER models

### ISSUE THREAD

**Issue by wizrds** [huggingface/text-embeddings-inference#282]
### Model description

Forgive me if I am mistaken, but is it feasible to implement the mechanisms needed to support a model such as [https://huggingface.co/urchade/gliner_large-v2](https://huggingface.co/urchade/gliner_large-v2) to perform NER on an input text and return the resulting prediction? As far as I understand TEI is geared primarily towards embeddings and reranking but I was just curious if it was at all possible to add support for other types of models easily or would I be better off writing my own server?

### Open source status

- [x] The model implementation is available
- [x] The model weights are available

**Comment by OlivierDehaene** [comment]
I don't think NER is something that should be included in the scope of this repo.
