### ISSUE TITLE
Go Client

### ISSUE THREAD

**Issue by sam-ulrich1** [huggingface/text-embeddings-inference#3]
### Feature request

I built a Go client for TEI here:
https://github.com/Gage-Technologies/tei-go

Not sure if you want to link it or have any advice on the stability of the OpenAPI

### Motivation

---

### Your contribution

---

**Comment by OlivierDehaene** [comment]
Thanks!
The API will remain stable between minor versions. 
For majors, you can expect the API to be backward compatible.

**Comment by sam-ulrich1** [comment]
@OlivierDehaene I made a python client as well: https://github.com/Gage-Technologies/tei-python
I was going to publish it but then I realized you might want to take ownership of it. Should I publish it or would you/HF like to roll it out and keep it in house

**Comment by OlivierDehaene** [comment]
Thanks for this!
For now we want to consolidate on the official `huggingface-hub` client.

```python
from huggingface_hub import InferenceClient

client = InferenceClient()
client.feature_extraction("What is deep learning?", model="http://localhost:3000")
```

**Comment by sam-ulrich1** [comment]
Ahh! I was unaware that client existed
