### ISSUE TITLE
Could not start backend: Runtime compute cap 75 is not compatible with compile time compute cap 80

### ISSUE THREAD

**Issue by llealgt** [huggingface/text-embeddings-inference#30]
### System Info

ext-embeddings-inference as of 2023-10-19, plattform: AWS  instance type: ml.g4dn.xlarge

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I'm trying to use the text embeddings as part of a RAG system running on AWS Sagemaker, when trying the official instructions running:

```
model=BAAI/bge-large-en-v1.5
revision=refs/pr/5
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all -p 8080:80 -v $volume:/data --pull always ghcr.io/huggingface/text-embeddings-inference:0.2.2 --model-id $model --revision $revision
```

I get:
```
Error: Could not create backend

Caused by:
    Could not start backend: Runtime compute cap 75 is not compatible with compile time compute cap 80
```
The command is executed in an AWS instance type: ml.g4dn.xlarge https://instances.vantage.sh/aws/ec2/g4dn.xlarge 

Are there any prerrequisites or additional setup? or maybe this is not the best approach to run the text-embeddings-inference  inside AWS?(would appreciate if anyone has suggestions)

### Expected behavior

The docker run command starts and it successfully accepts requests

**Comment by OlivierDehaene** [comment]
You should use the `turing` variant of the docker image on g4 as it uses T4 GPUs.

**Comment by llealgt** [comment]
@OlivierDehaene that worked, thanks. May I suggest adding a comment on the README to clarify that? 

Specifically something like this:

**Docker**
In the following code snippet replace the image name  ghcr.io/huggingface/text-embeddings-inference:0.2.2 with your specific variant depending on your GPU architecture, a list of available images can be found in "Docker Images"

**Comment by OlivierDehaene** [comment]
Sure! 
Would you like to open a PR?

**Comment by llealgt** [comment]
Ok, Will do later today. Thanks
