### ISSUE TITLE
Support nvidia/NV-Embed-v1

### ISSUE THREAD

**Issue by lzhengning** [huggingface/text-embeddings-inference#309]
### Model description

NV-Embed, introduced by Nvidia, is a generalist embedding model that ranks No. 1 on the MTEB Benchmark. 

[NV-Embed: Improved Techniques for Training LLMs as Generalist Embedding Models](https://arxiv.org/pdf/2405.17428)

The model is promising to be one of the best choice in production. It would be helpful if text-embeddings-inference support NV-Embed.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

model card: https://huggingface.co/nvidia/NV-Embed-v1

**Comment by OlivierDehaene** [comment]
> that ranks No. 1 on the MTEB Benchmark.

It's 4th actually, behind https://huggingface.co/Salesforce/SFR-Embedding-2_R which is supported.

> The model is promising to be one of the best choice in production. 

I wouldn't say so. The model is huge and therefore crazy expensive to run compared to small bert models.
