### ISSUE TITLE
Flash attention is not installed.

### ISSUE THREAD

**Issue by zhangdanfeng888** [huggingface/text-embeddings-inference#317]
I run this:
text-embeddings-router --model-id Salesforce/SFR-Embedding-Mistral --port 8080 --dtype float16

Then I get the following error:
![image](https://github.com/huggingface/text-embeddings-inference/assets/41187774/b2e01657-b7c4-4e45-8b09-90aaecf29fb5)
I have installed flash-attn:
![image](https://github.com/huggingface/text-embeddings-inference/assets/41187774/1497a980-6c14-4abd-86c7-b82ba59a74e8)

The same error when I run: text-embeddings-router --model-id Salesforce/SFR-Embedding-2_R --port 8080 --dtype float16
What's wrong?

**Comment by OlivierDehaene** [comment]
How did you install TEI? 
[Did you install it with cuda support?](https://github.com/huggingface/text-embeddings-inference?tab=readme-ov-file#cuda)
Do you have a supported GPU (cuda capability > 7.5)?

**Comment by zhangdanfeng888** [comment]
> How did you install TEI? [Did you install it with cuda support?](https://github.com/huggingface/text-embeddings-inference?tab=readme-ov-file#cuda) Do you have a supported GPU (cuda capability > 7.5)?

I install TEI with your step CUDA: cargo install --path router -F candle-cuda-turing -F http --no-default-features, my CUDA version is 12.4 and also add the nvidia binaries to path. My GPU is 3080, is it enough?

**Comment by OlivierDehaene** [comment]
Use `cargo install --path router -F candle-cuda -F http --no-default-features` instead. 
Note the `candle-cuda` instead of `candle-cuda-turing`.

A 3080 is not a turing GPU but an Ampere one.

**Comment by OlivierDehaene** [comment]
The `candle-cuda-turing` feature should only be used for old GPUs like T4s.
Also, 1.3 had a bug for mistral. I strongly advise you to update either to latest or 1.4.

**Comment by zhangdanfeng888** [comment]
Okay, I will try 1.4 via cargo install --path router -F candle-cuda -F http --no-default-features, thanks a lot
