### ISSUE TITLE
get (https://huggingface.co/BAAI/bge-reranker-v2-m3/resolve/main/config.json) error

### ISSUE THREAD

**Issue by kennard520** [huggingface/text-embeddings-inference#325]
### System Info

![image](https://github.com/huggingface/text-embeddings-inference/assets/46671069/7260efeb-4c91-4561-acbd-34e31de7f403)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus all -p 8080:80 -v /root/model_data:/data ghcr.io/huggingface/text-embeddings-inference:1.4 --model-id BAAI/bge-reranker-v2-m3 --revision main

### Expected behavior

Can I download the file  and mount to docker ?

**Comment by OlivierDehaene** [comment]
> Can I download the file and mount to docker ?

Yes you can! I added some docs [here](https://github.com/huggingface/text-embeddings-inference?tab=readme-ov-file#air-gapped-deployment).
