### ISSUE TITLE
Sentence Transformers based mpnet models

### ISSUE THREAD

**Issue by fozziethebeat** [huggingface/text-embeddings-inference#33]
### Feature request

The [Sentence Transformers](https://sbert.net/docs/pretrained_models.html) based mpnet models are pretty popular for fast and cheap embeddings.  It would be really helpful to support these, at a minimum those using the mpnet architecture, within the text embedding interface.  

### Motivation

As per [sentence-transformers/multi-qa-mpnet-base-cos-v1](https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-cos-v1) these models are still pretty popular.  For anyone using them in production with a semantic search stack, it'd be preferable to support these models with a much faster inference stack than migrate to a new embedding model that might have different performance characteristics.

### Your contribution

Once a CONTRIBUTING.md is written (it appears to not exist at the time of writing) I likely can find time to contribute to making this happen.  I would benefit from some details about code organization and style preferences.

**Comment by fozziethebeat** [comment]
Ah geez, I saw there's a different category for this type of request.  Sorry.

**Comment by xfalcox** [comment]
@OlivierDehaene sorry for the direct ping, but could you share a spit ball guess on how hard would be to add support for `all-mpnet-base-v2` ? Wondering if this is something we could try, wait or give up.

**Comment by OlivierDehaene** [comment]
It should be ok to add. Candle and pytorch are not Iso in features but it should have everything to support it. You wont be able to use flash attention though so it will be slower than other models.

**Comment by xfalcox** [comment]
> You wont be able to use flash attention though so it will be slower than other models.

Thanks for mentioning that. In that case it may be worth to bite the bullet and migrate now to BGE.

**Comment by OlivierDehaene** [comment]
Well the model needs to be ported from torch to candle which, depending on the model can take from one hour up to a day.
We do not have an equivalent of AutoModel.

In the specific case of mpnet, the only thing that is missing is relative attention. It will be slow because it biases the QxK matrix therefore you cannot use flash attention.
