### ISSUE TITLE
GPU memory usage is limited

### ISSUE THREAD

**Issue by chiosChen** [huggingface/text-embeddings-inference#330]
### System Info

image: ghcr.io/huggingface/text-embeddings-inference:turing-1.4
gpu: T4
model: bge-m3

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus all -p 8080:80 -v ~/models/bge-m3:/models/bge-m3 --model-id /models/bge-m3 --dtype float16 --pooling cls 

### Expected behavior

GPU memory is not fully used

**Comment by OlivierDehaene** [comment]
Why would GPU memory be fully used?

**Comment by chiosChen** [comment]
> Why would GPU memory be fully used? Do you also expect every program on your computer to use all your memory?

Sorry, I didn't make my question clear. We are doing load tests to determine the resources needed to reach the target RPS. Hence, we want each GPU is fully utilized. If the memory usage is capped, the maximum batch size is also reduced.

**Comment by chiosChen** [comment]
I tried --max-batch-tokens, --max-client-batch-size, --max-batch-requests, but didn't worker

**Comment by OlivierDehaene** [comment]
I still fail to understand the why memory matters in this scenario.
What you want is to max out the GPU utilisation. Are you saying that the utilisation is low?

**Comment by driphireweb** [comment]
I had a similar question, is it normal to have ~10% gpu utilization between both text-embeddings processes?

<img width="737" alt="Screenshot 2024-07-22 at 8 45 51 PM" src="https://github.com/user-attachments/assets/8c79314a-308c-42a2-b220-08e5b1fa422a">

**Comment by nauyan** [comment]
@driphireweb @chiosChen any update on the above? Were you folks able to utilize ~100% memory
