### ISSUE TITLE
rerank model large batch request only use single cpu(for tokenizer?)

### ISSUE THREAD

**Issue by anaivebird** [huggingface/text-embeddings-inference#339]
### System Info

![dc193301870fd3b8c81e6ddfa600fe0](https://github.com/user-attachments/assets/86a74d32-62d5-4542-892f-4125cc44a5fd)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

`
import requests
import threading
import random
import string

headers = {
    'Content-Type': 'application/json',
}

texts = [
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '芒果是' * 150,
    '西瓜是' * 150,
    '西瓜是' * 150
]

texts = [''.join(random.choices(string.ascii_letters, k=10)) + x for x in texts]

print(texts)
json_data = {
    'query': '什么是西瓜',
    'texts': texts,
}

def send_request():
    from time import time
    begin = time()
    response = requests.post('http://10.104.88.202:38080/rerank', headers=headers, json=json_data)
    # print(response.json())
    end = time()
    print(end - begin)

threads = []

for _ in range(2):
    thread = threading.Thread(target=send_request)
    threads.append(thread)
    thread.start()

for thread in threads:
    thread.join()
`

### Expected behavior

use multiple cpu core

**Comment by OlivierDehaene** [comment]
How do you launch TEI?

**Comment by anaivebird** [comment]
`docker run --gpus "device=0" -p 38080:80 -v $PWD/data:/data ghcr.io/huggingface/text-embeddings-inference:1.2 --model-id /data/bge-reranker-large`

**Comment by imotai** [comment]
> https://github.com/hyperium/tonic/issues/1405

This thread may be helpful

**Comment by OlivierDehaene** [comment]
The tokenization for sure use multiple cores. There is multi threading inside the tokenizers lib + we have multiple workers.

Then there is only a single thread that launch the kernels on the device.
