### ISSUE TITLE
total time not equals to inference + queue+ tokenizer time

### ISSUE THREAD

**Issue by anaivebird** [huggingface/text-embeddings-inference#340]
### System Info

![f6797fac47fd762e3b1583599b7f922](https://github.com/user-attachments/assets/3fabcfde-8386-4347-9f01-edd6d2fb4bef)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

send some request

### Expected behavior

total time equals to inference + queue+ tokenizer time

**Comment by OlivierDehaene** [comment]
Not if you send your requests in a batch.
