### ISSUE TITLE
CUDA_COMPUTE_CAP doesn't take effect in Dockerfile-cuda

### ISSUE THREAD

**Issue by PeterYang12** [huggingface/text-embeddings-inference#381]
### System Info

I am using H100. 
CUDA_COMPUTE_CAP=90

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

My Dockerfile, is not related to TEI, but here to demonstrate the bug
docker build -f Dockerfile --build-arg CUDA_COMPUTE_CAP=90 .
```
FROM ubuntu:22.04 AS stage1
ARG CUDA_COMPUTE_CAP
RUN echo ${CUDA_COMPUTE_CAP}

FROM stage1 AS stage2
#ARG CUDA_COMPUTE_CAP
RUN echo ${CUDA_COMPUTE_CAP}
```

The stage won't echo 90 if not specifiy CUDA_COMPUTE_CAP in stage2.

Similar issue: https://stackoverflow.com/questions/53681522/share-variable-in-multi-stage-dockerfile-arg-before-from-not-substituted

### Expected behavior

N/A

**Comment by OlivierDehaene** [comment]
I don't know if this was updated recently or not but it doesn't seem to be true.

`Dockerfile`
```Dockerfile
FROM ubuntu as base

ARG COMPUTE_CAP

FROM base

RUN echo ${COMPUTE_CAP} > compute_cap
```

```shell
docker build . -t test --build-arg COMPUTE_CAP=4
docker run test cat compute_cap
# 4
```

**Comment by OlivierDehaene** [comment]
[From the Docker doc](https://docs.docker.com/build/building/variables/):

```Dockerfile
#Once a build argument is declared or consumed in a stage, it's automatically inherited by child stages.

FROM alpine AS base
# Declare the build argument in the build stage
ARG NAME="joe"

# Create a new stage based on "base"
FROM base AS build
# The NAME build argument is available here
# since it's declared in a parent stage
RUN echo "hello $NAME!"
```
