### ISSUE TITLE
Paged attention optimization for memory efficient continuously batched requests

### ISSUE THREAD

**Issue by jorgeantonio21** [huggingface/text-embeddings-inference#391]
### Feature request

I am interested in integrating this repository into my project infrastructure (which is fully written in Rust). I am interested in memory efficient continuous batching. 

Currently, flash attention 2 supports paged attention, that is a block pagination method (used by vLLM) for non-contiguous memory access of the KV cache. 

Even though candle does not support paged attention with flash attention2, I have worked on a library that implements precisely this (in Rust), which is heavily inspired by the already existing work in Candle.

Would this feature desirable to have in for the `text_embeddings-inference` repository ? If so, would it be possible to have an optional `paged_attention` flag to route these requests to a different repository from Candle ?

### Motivation

Introducing memory efficient non-contiguous memory access, through memory block pagination.

### Your contribution

I can work on introducing this feature, if it is desirable. If paged attention is required by the user of the library, then a call needs to be done to an external library other than Candle, for the time being.

**Comment by OlivierDehaene** [comment]
Paged attention is not required for TEI as it does not use a KV cache.

**Comment by YjyJeff** [comment]
Hi @OlivierDehaene , I'm looking into the performance of Qwen3 for large-scale embedding tasks. Given that it is a decoder-only model, does it benefit from KV caching?
