### ISSUE TITLE
why cause 413?

### ISSUE THREAD

**Issue by lzy199qwe** [huggingface/text-embeddings-inference#50]
I get this "Failed to buffer the request body: length limit exceeded" when use requests.post
is my inputs too large?

**Comment by handrew** [comment]
I got this error when sending an input with a batch size that was too large. The default batch size set in the command line arguments is 32; you can increase it.

**Comment by lzy199qwe** [comment]
> I got this error when sending an input with a batch size that was too large. The default batch size set in the command line arguments is 32; you can increase it.

I have increased --max-client-batch-size  to 1024, but still got this problem..

**Comment by OlivierDehaene** [comment]
Axum's (the webserver we are using internally) default limit is 2MB. How much data are you sending? 
Maybe you can chunk the request into smaller ones?

**Comment by lzy199qwe** [comment]
> Axum's (the webserver we are using internally) default limit is 2MB. How much data are you sending? Maybe you can chunk the request into smaller ones?

thx

**Comment by zhaozhiming** [comment]
To avoid encountering an error, consider setting the `truncate` parameter to true.

**Comment by markab21** [comment]
> Axum's (the webserver we are using internally) default limit is 2MB. How much data are you sending? Maybe you can chunk the request into smaller ones?

We are using text-embeddings-inference to batch-encode documents. We hit this limit if we send more than a few at a time which has made the platform crippled for us. Can we send an environment variable or flag to increase the memory limit? 2MB is not that large of a payload.

**Comment by OlivierDehaene** [comment]
2mb is ~1 million chars. 
What type of payload are you sending? It me be more sensible to divide this payload in multiple batches instead.

**Comment by pseudotensor** [comment]
I'm hitting 413 from client without any errors in server and not sure what to do.  I have client batch of 4096 and max batch of 2097152 i.e.
```
docker run -d --gpus '"device=0"' --shm-size 3g -v $HOME/.cache/huggingface/hub/:/data -p 5555:80 --pull always ghcr.io/huggingface/text-embeddings-inference:0.6 --model-id BAAI/bge-large-en-v1.5 --revision refs/pr/5 --hf-api-token=$HUGGINGFACE_API_TOKEN --max-client-batch-size 4096 --max-batch-tokens=2097152
```

I check that client only sends 4096 batch for model with 512 tokens, and pass truncate=true that is respected according to logs for other cases.  However, still hit this client error:
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: http://localhost:5555/

```

**Comment by OlivierDehaene** [comment]
A batch size of 4096 with 512 tokens means that you are sending more than 2mb of data per request which is not allowed. 
You should split this batch in multiple smaller ones.

**Comment by pseudotensor** [comment]
Ok thanks.  I'm not super familiar with the limits, and google says it's 10MB, but could you explain where 2MB comes from?  Is that limit you implemented?

**Comment by OlivierDehaene** [comment]
https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html

**Comment by pseudotensor** [comment]
Thanks!
