### ISSUE TITLE
Truncation does not work with batching

### ISSUE THREAD

**Issue by axenov** [huggingface/text-embeddings-inference#52]
### System Info

The `tructate` parameter is not recognized if the list of texts is sent.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

1. Run the docker container via `docker run --gpus all -p 5000:80 -v $volume:/data --pull always ghcr.io/huggingface/text-embeddings-inference:latest --model-id $model --revision $revision`
2. Make a python post request  `requests.post(f"{URL}/embed", json={"inputs":[test*1000], "truncate": True}).json()` 
3. Then I see the following error  `{'error': 'Input validation error: `inputs` must have less than 512 tokens. Given: 1002', 'error_type': 'Validation'}`

### Expected behavior

The embedding of the truncated text as I have with `requests.post(f"{URL}/embed", json={"inputs":test*1000, "truncate": True})`

**Comment by OlivierDehaene** [comment]
Indeed it is a regression.
Fixed by https://github.com/huggingface/text-embeddings-inference/commit/04f94f6b6a30ebc40ef35180a46d851b247b3a53
