### ISSUE TITLE
Reduce CUDA version to be the same as TGI

### ISSUE THREAD

**Issue by taoari** [huggingface/text-embeddings-inference#54]
### System Info

TEI: 0.3.0
GPU A100
CUDA VERSION 12.1

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I noticed that the Cuda version of the docker image requires CUDA 12.2. However, this version of CUDA is too high for many servers. Is it possible to reduce the CUDA requirement to 11.8 as TGI?

### Expected behavior

Change the minimum CUDA version to 11.8 as TGI.

**Comment by handrew** [comment]
I had a similar problem. I think you can solve it by simply updating your NVIDIA driver. Supposedly, `nvidia-driver-525` should work for CUDA 12.2, but I had to `sudo apt install nvidia-driver-535`. After installing and then restarting my GPU, it ended up working. But if you are running a serverless solution then it might be hard to automatically restart the instance.

**Comment by taoari** [comment]
@handrew Thanks. For a server, one usually does not have the privilege of sudo. That's why I proposed this issue.

CUDA 12.2 was released in June 2023. Many servers are not updated yet. It is quite strange that a library would set the minimum requirement to the latest version of Cuda driver.

**Comment by handrew** [comment]
@taoari yeah I agree, not ideal.

Though, I'm not sure what servers you're using, but if you're setting them up with a cloud provider you should have sudo access. And if not sudo access, some allow you to just `apt install` anyway.

**Comment by OlivierDehaene** [comment]
I agree that 12.2 might be a bit too early. 
We can lower to 12.0 but not 11.x. TGI will be upgraded to 12.0 soon to support newer hardwares.

**Comment by OlivierDehaene** [comment]
The minimum cuda version was lowered to 12.0.
