### ISSUE TITLE
`truncate` not working

### ISSUE THREAD

**Issue by lzy199qwe** [huggingface/text-embeddings-inference#56]
### System Info

docker : ghcr.io/huggingface/text-embeddings-inference:turing-0.3.0
model : https://huggingface.co/intfloat/multilingual-e5-base

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. docker run -i -t --rm --name embed-model --runtime=nvidia --gpus='"device=1"' -e LOG_LEVEL=debug -p 18081:80 -v /multilingual-e5-base:/embed_model/ --shm-size="16gb" ghcr.io/huggingface/text-embeddings-inference:turing-0.3.0 --model-id /embed_model

2. prepare inputs:
input1 = 'hello world'*7777
input2 = ['helloworld'*7777]

3. requests.post(url='http://localhost:18080', json={'inputs': input1, "truncate":True})   gets correct answer
4. requests.post(url='http://localhost:18080', json={'inputs': input2, "truncate":True})   gets {"error":"Input validation error: `inputs` must have less than 512 tokens. Given: 31110","error_type":"Validation"}

### Expected behavior

all correct

**Comment by OlivierDehaene** [comment]
Yes it was fixed by https://github.com/huggingface/text-embeddings-inference/commit/04f94f6b6a30ebc40ef35180a46d851b247b3a53.

You can use ghcr.io/huggingface/text-embeddings-inference:turing-sha-04f94f6 instead and we will make a release soon.

**Comment by lzy199qwe** [comment]
> Yes it was fixed by [04f94f6](https://github.com/huggingface/text-embeddings-inference/commit/04f94f6b6a30ebc40ef35180a46d851b247b3a53).
> 
> You can use ghcr.io/huggingface/text-embeddings-inference:turing-sha-04f94f6 instead and we will make a release soon.
 I appreciate it.
