### ISSUE TITLE
CPU mkl build fail

### ISSUE THREAD

**Issue by yao-matrix** [huggingface/text-embeddings-inference#64]
### System Info

Hi, I am trying to follow the README to build a CPU version TEI.

And When I follow the command in the README  `cargo install --path router -F candle -F mkl`, there is a link issue as below
"  Installing text-embeddings-router v0.3.0 (/workspace/matrix/text-embeddings-inference/router)
    Updating git repository `https://github.com/OlivierDehaene/candle`
    Updating git repository `https://github.com/OlivierDehaene/cudarc`
    Updating crates.io index
warning: Patch `candle-flash-attn v0.3.0 (https://github.com/OlivierDehaene/candle?rev=9f2b4081b83a0e47ec1b12caa71d3cac7cc2161e#9f2b4081)` was not used in the crate graph.
Patch `cudarc v0.9.15 (https://github.com/OlivierDehaene/cudarc?rev=8be6ff46e4a2014fb563570e0d206c09aea88152#8be6ff46)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling text-embeddings-router v0.3.0 (/workspace/matrix/text-embeddings-inference/router)
error: linking with `cc` failed: exit status: 1

...
          /root/.cargo/git/checkouts/candle-2c6db576e0f06e81/9f2b408/candle-core/src/mkl.rs:134: undefined reference to `dgemm_'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
" 
Seems it cannot link with mkl library. 

And 1) when I remove `-F mkl`, everything will be fine.
        2) I also tried the way is candle to add "extern crate intel_mkl_src;" at the top of the main.rs of router folder, seems doesn't work.

Do you have some suggestions on what should I do next to fix this issue? Thx.

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

cargo install --path router -F candle -F mkl

### Expected behavior

Compile pass and get final binary

**Comment by yao-matrix** [comment]
@OlivierDehaene

**Comment by OlivierDehaene** [comment]
In some cases, you need to install mkl manually.
See: https://github.com/huggingface/candle/issues/443

```shell
wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
| gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null && \
  echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | \
  sudo tee /etc/apt/sources.list.d/oneAPI.list
  
  sudo apt-get update
  sudo apt-get install -y intel-oneapi-mkl-devel
  sudo apt-get install -y libomp-dev
```

**Comment by yao-matrix** [comment]
Thx, it works.

**Comment by citkane** [comment]
I also had to:
```
git checkout <version>
```

Sounds obvious, but cost me half a day...
