### ISSUE TITLE
Add support for cross-encoder models

### ISSUE THREAD

**Issue by peakji** [huggingface/text-embeddings-inference#75]
### Feature request

Add support for cross-encoder models, such as [BAAI/bge-reranker-base](https://huggingface.co/BAAI/bge-reranker-base) and various models from the [Sentence Transformers - Cross-Encoders](https://huggingface.co/cross-encoder) project.

A new API endpoint could also be added, for example:
```bash
curl 127.0.0.1:8080/predict \
    -X POST \
    -d '{"inputs": ["What is Deep Learning?", "Deep Learning is ..."]}' \
    -H 'Content-Type: application/json'
```

### Motivation

In vector search, we often employ a cross-encoder model for reranking the top-k results, which typically yields better performance compared to using embedding models alone.

### Your contribution

Cross-encoder models share similar model structures with embedding models, suggesting that some optimizations could potentially be reused.

**Comment by exceedzhang** [comment]
<img width="1512" alt="image" src="https://github.com/huggingface/text-embeddings-inference/assets/4583537/b1ade35b-8174-4087-8a69-057eeced3d4b">
[BAAI/bge-reranker-base](https://huggingface.co/BAAI/bge-reranker-large) is not worked. Why? @peakji

**Comment by peakji** [comment]
@exceedzhang The original repo does not have a fast tokenizer, you can download `tokenizer.json` from @OlivierDehaene's [pull request](https://huggingface.co/BAAI/bge-reranker-large/blob/refs%2Fpr%2F4/tokenizer.json).
