### ISSUE TITLE
As batch_size increases, the inference time lengthens

### ISSUE THREAD

**Issue by stwl1999** [huggingface/text-embeddings-inference#83]
Author, I was testing TEI and found that as batch_size increases, inference time also increases. At a certain batch_size, the performance is not as good as sentence_transformer.
Is the program now unable to support batch parallelism?

**Comment by OlivierDehaene** [comment]
> as batch_size increases, inference time also increases. 

Latency increases but throughput also increases.

For example with imaginary numbers:
- batch size 1: latency 5 ms => throughput (1000 / 5) * batch size = 200 req/secs
- batch size 32: latency 20 ms => throughput (1000 / 20) * 32 = 1600 req/secs

What is the point you are trying to make?
